// Generated by Wrangler by running `wrangler types`
// (manually extended with secrets — `wrangler types` does not emit secret bindings)

interface Env {
	// Secret, set via `wrangler secret put YOUTUBE_API_KEY`. Backs GET /team-videos:
	// resolves each club's YouTube uploads + recent videos via the YouTube Data API.
	YOUTUBE_API_KEY: string;
}
