#!/usr/bin/env node
// NWSL Trivia pool health check — NO SILENT FAILURES gate (roadmap #2).
//
// The yearly Trivia pool is generated by a routine, grouped by the proxy into biweekly rounds, and stored at
// KV `trivia-pool-v2` (binding FEED_TAGS). A missed annual refresh, a stale season, or a structurally-off
// grouping would degrade the game silently (the serving path WRAPS to a prior year rather than erroring). This
// gate reads the stored doc DIRECTLY from KV and asserts the invariants the grouper is supposed to guarantee,
// so a wrong-season or malformed pool fails loudly BEFORE anyone plays it.
//
// Usage:
//   node scripts/health_check_trivia.mjs            # against the remote KV (production)
//   npm run healthcheck                             # runs in the chain
// (Reads KV via `wrangler kv key get` — needs wrangler auth, like the other loaders.)

import { execFileSync } from "node:child_process";

const KV_KEY = "trivia-pool-v2";
const KV_BINDING = "FEED_TAGS";
const CATEGORIES = new Set(["leagueHistory", "playerFacts", "venues", "rules", "records", "teamHistory"]);
const DIFFICULTIES = new Set(["easy", "medium", "hard"]);

// Must match DEFAULT_GROUP_CONFIG in src/trivia.ts.
const CFG = {
  roundCount: 30,
  perRound: 10,
  difficultyTarget: { easy: 2, medium: 4, hard: 4 },
  funFactsPerRound: 2,
  categoryMaxPerRound: 3,
  categoryMinDistinct: 4,
};

const MONTH = new Date().getUTCMonth() + 1;
const YEAR = new Date().getUTCFullYear();
const IN_SEASON = MONTH >= 3 && MONTH <= 11;
const CURRENT_SEASON = MONTH < 3 ? YEAR - 1 : YEAR; // Jan/Feb still count as the prior NWSL season

const failures = [];
const warn = (m) => console.log(`  ⚠️  ${m}`);
const failCheck = (m) => { failures.push(m); console.log(`  ❌ ${m}`); };
const ok = (m) => console.log(`  ✅ ${m}`);

console.log(`\nNWSL Trivia pool health check — KV ${KV_BINDING}/${KV_KEY} (${IN_SEASON ? "in-season" : "offseason"}, current season ${CURRENT_SEASON})\n`);

// --- Read the v2 doc from KV --------------------------------------------------
let raw;
try {
  raw = execFileSync("npx", ["wrangler", "kv", "key", "get", KV_KEY, "--binding", KV_BINDING, "--remote"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
} catch (e) {
  // A never-published pool is a WARN pre-launch (the app bridges on the flat v1 pool), a FAIL in-season once
  // the pipeline is meant to be live.
  const msg = `no ${KV_KEY} in KV (${(e.stderr || e.message || "").toString().split("\n")[0]})`;
  if (IN_SEASON) failCheck(`${msg} — the yearly pool was never published`);
  else warn(`${msg} — offseason / pre-launch; the app bridges on the flat pool`);
  process.exit(failures.length ? 1 : 0);
}

let doc;
try {
  doc = JSON.parse(raw);
} catch (e) {
  failCheck(`${KV_KEY} is not valid JSON: ${e.message}`);
  process.exit(1);
}

// --- Season freshness ---------------------------------------------------------
if (!Number.isInteger(doc.season)) failCheck(`doc.season is not an integer (${doc.season})`);
else if (doc.season < CURRENT_SEASON) failCheck(`stale pool: season ${doc.season} < current ${CURRENT_SEASON} — the annual refresh was missed (serving is wrapping to an old year)`);
else ok(`season ${doc.season} (current ${CURRENT_SEASON})`);

// --- Structure + invariants ---------------------------------------------------
const rounds = doc.rounds && typeof doc.rounds === "object" ? doc.rounds : null;
if (!rounds) {
  failCheck("doc.rounds is missing/not an object");
  process.exit(1);
}
const keys = Object.keys(rounds);
if (keys.length < CFG.roundCount) failCheck(`only ${keys.length} rounds (want ≥${CFG.roundCount})`);
else ok(`${keys.length} rounds published`);

const allIds = new Set();
let dupIds = 0;
let malformedRounds = 0;
let constraintViolations = 0;
let unsourced = 0;

for (const key of keys) {
  const round = rounds[key];
  if (!Array.isArray(round) || round.length !== CFG.perRound) {
    malformedRounds++;
    continue;
  }
  const diff = { easy: 0, medium: 0, hard: 0 };
  const cat = {};
  let fun = 0;
  for (const q of round) {
    if (allIds.has(q.id)) dupIds++;
    allIds.add(q.id);
    if (typeof q.source !== "string" || !q.source.trim()) unsourced++;
    if (DIFFICULTIES.has(q.difficulty)) diff[q.difficulty]++;
    if (CATEGORIES.has(q.category)) cat[q.category] = (cat[q.category] || 0) + 1;
    if (q.flavor === "funFact") fun++;
  }
  const distinct = Object.keys(cat).length;
  const maxCat = Math.max(0, ...Object.values(cat));
  if (
    diff.easy !== CFG.difficultyTarget.easy ||
    diff.medium !== CFG.difficultyTarget.medium ||
    diff.hard !== CFG.difficultyTarget.hard ||
    fun < CFG.funFactsPerRound ||
    distinct < CFG.categoryMinDistinct ||
    maxCat > CFG.categoryMaxPerRound
  ) {
    constraintViolations++;
    if (constraintViolations <= 3) warn(`round ${key} off-spec: diff=${JSON.stringify(diff)} fun=${fun} distinctCats=${distinct} maxPerCat=${maxCat}`);
  }
}

if (dupIds > 0) failCheck(`${dupIds} DUPLICATE question id(s) across the year — the no-in-year-repeat invariant is broken`);
else ok(`no in-year repeats (${allIds.size} distinct question ids)`);

if (malformedRounds > 0) failCheck(`${malformedRounds} round(s) are not exactly ${CFG.perRound} questions`);
else ok(`every round has exactly ${CFG.perRound} questions`);

if (unsourced > 0) failCheck(`${unsourced} question(s) missing a source URL`);
else ok(`every question carries a source`);

if (constraintViolations > 0) failCheck(`${constraintViolations} round(s) violate the difficulty/fun/category spec`);
else ok(`every round meets the difficulty ${JSON.stringify(CFG.difficultyTarget)} + ${CFG.funFactsPerRound} fun + ≥${CFG.categoryMinDistinct}-category spec`);

console.log("");
if (failures.length) {
  console.error(`❌ FAIL — ${failures.length} issue(s):\n   - ${failures.join("\n   - ")}\n   Regenerate + re-ingest via POST /trivia/ingest (see docs/fan-zone.md).`);
  process.exit(1);
}
console.log("✅ PASS — Trivia pool is current-season, 30×10, no in-year repeats, sourced, and on-spec.\n");
